services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mern-backend
    command: npm run development
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mern-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: