services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mern-backend
    command: npm run development
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mern-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mern-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mern-mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: mern-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
